name: Unity Activation

on:
  workflow_dispatch:

env:
  UNITY_VERSION: "6000.1.0f1"

jobs:

  checklicense:
    name: Check for UNITY_LICENSE in GitHub Secrets
    runs-on: ubuntu-latest
    outputs:
      is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
    steps:
      - name: Check whether unity activation requests should be done
        id: checklicense_job
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          echo "Skip activation job: ${{ env.UNITY_LICENSE != '' }}"
          if [ -n "${{ env.UNITY_LICENSE }}" ]; then
            echo "is_unity_license_set=true" >> $GITHUB_OUTPUT
          else
            echo "is_unity_license_set=false" >> $GITHUB_OUTPUT
          fi

  activation:
    needs: checklicense
    if: needs.checklicense.outputs.is_unity_license_set == 'false'
    name: Request manual activation file :key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v4.3.0
        with:
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Upload .alf artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityActivationFile
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
