name: Activate Unity License

on:
  workflow_dispatch: {}  # Pour le déclencher manuellement depuis GitHub

jobs:
  activate:
    name: Request and Upload Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Request Activation File
        id: request_activation
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.0.49f1  # Remplace par ta version Unity

      - name: Upload Activation File
        uses: actions/upload-artifact@v3
        with:
          name: unity_activation_file
          path: ${{ steps.request_activation.outputs.filePath }}
