name: License Activation

on:
  schedule:
    - cron: "0 0 * * 1" # Exécution chaque semaine
  workflow_dispatch: # Déclenchement manuel

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UNITY_VERSION: 2023.2.20f1

jobs:
  request_alf:
    name: Request .alf file
    runs-on: ubuntu-latest
    outputs:
      alf: ${{ steps.output.outputs.alf }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Request manual activation file
        id: alfFile
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Upload .alf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: unity-alf
          path: unity.alf

      - name: Output alf path
        id: output
        run: echo "::set-output name=alf::unity.alf"

  acquire_ulf:
    needs: [request_alf]
    name: Acquire .ulf file
    runs-on: ubuntu-latest
    steps:
      - name: Download .alf artifact
        uses: actions/download-artifact@v4
        with:
          name: unity-alf

      - name: Mettre à jour le secret UNITY_LICENSE (optionnel)
        id: update_secret
        run: echo "Téléchargez le .ulf généré et stockez son contenu dans le secret UNITY_LICENSE pour automatiser l'activation."
